name: CI/CD
on:
  push:
    branches: [master]

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        run: |
          python -m unittest discover tests/
  code_checking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8
      - name: Run Checks
        run: |
          mypy tests/ src/
          flake8 --ignore=E501 tests/ src/
  deployment:
    needs: unit_testing
    runs-on: ubuntu-latest
    steps:
      - name: Fresh Repo Clone & Install
        uses: appleboy/ssh-action@master
        with:
          host: 54.82.207.212
          username: app-deploy
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            rm -rf Poketeams
            git clone https://github.com/AndrewGregorovic/Poketeams.git
            python3.8 -m venv /home/app-deploy/Poketeams/venv
            /home/app-deploy/Poketeams/venv/bin/pip3.8 install -r /home/app-deploy/Poketeams/requirements.txt